### ISSUE TITLE
truenas.services names

### ISSUE THREAD

**Issue by llinzen** [arensb/ansible-truenas#10]
I can not get the right names for the iscsi and smb services. I managed to get the others:
- ssh
 - nfs 
 - smartd 
 - ups 
 - ftp 
 - snmp

However none of my ideas for smb or iscsi have worked:
- smbd
- samba
- sambad
- smb
- SMB
- SMBd
- smb4
- iscsi
- iscsid

I am using Truenas Scale 23.10.1.3

**Comment by crpb** [comment]
https://www.truenas.com/docs/api/scale_websocket_api.html#service
`midclt call service.query |jq '.[]|.service'`
