### ISSUE TITLE
Exampe code for nfs module raises error when setting nfsv4

### ISSUE THREAD

**Issue by steven-ellis** [arensb/ansible-truenas#13]
The example code for configuring nfsv4 is throwing an error on TrueNAS Scale 23.10.2

```
    - name: Enable NFSv4
      arensb.truenas.nfs:
        nfsv4: yes
```

Error
```
    "module_stdout": "Traceback (most recent call last):\r\n  File \"/root/.ansible/tmp/ansible-tmp-1709435723.4626808-793846-169862083948011/AnsiballZ_nfs.py\", line 107, in <module>\r\n    _ansiballz_main()\r\n  File \"/root/.ansible/tmp/ansible-tmp-1709435723.4626808-793846-169862083948011/AnsiballZ_nfs.py\", line 99, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/root/.ansible/tmp/ansible-tmp-1709435723.4626808-793846-169862083948011/AnsiballZ_nfs.py\", line 47, in invoke_module\r\n    runpy.run_module(mod_name='ansible_collections.arensb.truenas.plugins.modules.nfs', init_globals=dict(_module_fqn='ansible_collections.arensb.truenas.plugins.modules.nfs', _modlib_path=modlib_path),\r\n  File \"<frozen runpy>\", line 226, in run_module\r\n  File \"<frozen runpy>\", line 98, in _run_module_code\r\n  File \"<frozen runpy>\", line 88, in _run_code\r\n  File \"/tmp/ansible_arensb.truenas.nfs_payload_c0ot8r0s/ansible_arensb.truenas.nfs_payload.zip/ansible_collections/arensb/truenas/plugins/modules/nfs.py\", line 112, in <module>\r\n  File \"/tmp/ansible_arensb.truenas.nfs_payload_c0ot8r0s/ansible_arensb.truenas.nfs_payload.zip/ansible_collections/arensb/truenas/plugins/modules/nfs.py\", line 84, in main\r\nKeyError: 'v4'\r\n",
```

**Comment by arensb** [comment]
This might be a difference between TrueNAS Core and Scale.

Could you please ssh to your TrueNAS machine, run `sudo /usr/local/bin/midclt call nfs.config |jq .` and share what it says?

**Comment by steven-ellis** [comment]
Slightly different path on TrueNas Scale - here is the response

```
/usr/bin/midclt call nfs.config |jq .
{
  "id": 1,
  "servers": 16,
  "udp": false,
  "allow_nonroot": false,
  "protocols": [
    "NFSV3",
    "NFSV4"
  ],
  "v4_v3owner": false,
  "v4_krb": false,
  "bindip": [],
  "mountd_port": null,
  "rpcstatd_port": null,
  "rpclockd_port": null,
  "mountd_log": false,
  "statd_lockd_log": false,
  "v4_domain": "",
  "v4_krb_enabled": false,
  "userd_manage_gids": false,
  "v4_owner_major": ""
}
```

**Comment by arensb** [comment]
Yeah, that's different from TrueNAS Core, which just has a boolean `v4` flag, which turns on NFS v4 in addition to v3, which is always enabled.

The fact that on Scale, `protocols` is a list of keywords suggests that it supports turning NFS v3 and v4 on and off independently, and perhaps other protocols as well. Can you confirm this? Is it possible to enable v4 but disable v3? If so, I'd have to rethink now this module works.

**Comment by steven-ellis** [comment]
Here is a screen shot from the webui. I can disable either protocol version or enable both

![Screenshot from 2024-03-06 20-42-26](https://github.com/arensb/ansible-truenas/assets/7764112/667922c1-49d9-463e-991a-251a15047271)

**Comment by arensb** [comment]
Okay, so Core 13.0 supports either v3 or v3+v4, while SCALE supports enabling and disabling each one individually.

So for the UI, I think it makes most sense to have an array of supported versions:

    - nfs:
        protocols:
        - NFSv3
        - NFSv4

On SCALE, this translates directly to the `protocols` array, while on CORE, three settings translate to a `v4` setting, and the fourth is illegal.

So I think the sensible thing is to allow either `protocols` or `v4`, but not both. The first thing the module does is to call `nfs.config`. The returned data structure should contain either `v4` or `protocols`, and that will tell us which version of the parameters to use.

**Comment by arensb** [comment]
So I think The Right Way to fix this is: allow either `nfsv4` or `protocols` (but not both). And internally, convert to a set: `nfsv4: true` is equivalent to `protocols: [ NFSV3, NFSV4]`, and `nfsv4: false` is equivalent to `protocols: [NFSV3]`.

Then, given this set, figure out what's set on the server and whether that differs from the desired state.

This is fine on paper, but leads to some fiddly code. But maybe it can be simplified with some helper functions.

**Comment by arensb** [comment]
I've pushed out [v1.9.2](https://github.com/arensb/ansible-truenas/releases/tag/v1.9.2), which incorporates this change.
