### ISSUE TITLE
Can't create password_disabled user if smb is enabled on the machine

### ISSUE THREAD

**Issue by MozzieBytes** [arensb/ansible-truenas#17]
Ran into the below issue when trying to create a password_disabled user on my Truenas box with smb shares. 

It seems by default truenas creates users with smb enabled for user ease.

Reading through the source code for this module, it seems like we just need to add support for this by passing an smb value into the API request.

```
fatal: [192.168.1.100]: FAILED! => {"changed": false, "msg": "Error creating user dockyard: midclt exited with status 1: \"b'[EINVAL] user_create.password_disabled: Password authentication may not be disabled for SMB users.\\n'\""}
```

Currently working on a fix for this as I can see through the source code how this can be resolved.

**Comment by arensb** [comment]
Closing as duplicate.

**Comment by MozzieBytes** [comment]
@arensb Have attached my proposed solution to the existing issue. 

Sorry for creating a duplicate issue
