### ISSUE TITLE
Cannot set Owner for newly created filesystems

### ISSUE THREAD

**Issue by brokoli18** [arensb/ansible-truenas#22]
It is currently not possible to set permissions when creating new datasets. This presents a problem when creating and exporting NFS mounts as by default the permissions are unsuitable.

It would be good to add this functionality in. I can have a go at this myslf when I have some time.

**Comment by arensb** [comment]
Can you elaborate? Which permissions are you referring to? Do you mean things like owner, group, and mode for the root directory of the newly-created dataset?

What exactly is the problem you're seeing? Do you have a playbook that replicates the problem?

**Comment by brokoli18** [comment]
@arensb 
1. When creating zfs datasets I want the ability to set the uid and gid of the owner as well as the access modes. Similar to what is available in `storage/pools/permissions` (essentially `chown user/group; chmod 0644`)
2. When creating NFS shares I want the ability to set the `maproot user` and `maproot group` options. Often NFS shares from truenas dont work for me without these options.

The reason I need these is that when creating datasets and nfs shares with default options and mounting them on clients, any attempts to interact with the filesystem result in permission denied errors as the user on the client and on the remote server don't match. I hope that makes sense.

**Comment by brokoli18** [comment]
After checking over the code I can see that it may already be possible, in which case it would be a good idea to update the documentation to reflect that.

**Comment by arensb** [comment]
> I want the ability to set the uid and gid of the owner as well as the access modes. Similar to what is available in `storage/pools/permissions` (essentially `chown user/group; chmod 0644`)

Why not just use `ansible.builtin.file`?

**Comment by arensb** [comment]
I'm not seeing a way to set ownership or permisssions when adding a datset in either the console, the TrueNAS API documentation, or `zfs create`. This suggests that the ownership and permissions are something set after creation. That is, you can achieve the desired effect with `truenas.filesystem` followed by `file`.

Unless there's something to be gained by rolling permissions into `truenas.filesystem`, I'd prefer not to complicate it this way.

**Comment by brokoli18** [comment]
Ah yes you are right, I didnt even consider using `ansible.builtin.file` for some reason. I think I can achieve the desired behavior using those, thanks. I will close this.
